version: '3.8'

services:
  wordpress:
    image: wordpress 
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      inception:
        ipv4_address: 172.16.0.4
    depends_on:
      - mariadb
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d
      - wordpress:/var/www/html/wordpress
    networks:
      inception:
        ipv4_address: 172.16.0.3
    depends_on:
      - wordpress
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      inception:
        ipv4_address: 172.16.0.2
volumes:
   database:
   wordpress:
networks:
  inception:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
