version: '3.8'

services:
  wordpress:
    image: wordpress 
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress-data:/var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      inception:
    depends_on:
      - mariadb
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      inception:
    depends_on:
      - wordpress
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      inception:
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/hbenfadd/data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/hbenfadd/data
      o: bind
networks:
  inception:
