version: '3.8'

services:
  wordpress:
    image: wordpress 
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      inception:
    depends_on:
      - mariadb
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      inception:
    depends_on:
      - wordpress
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      inception:
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/hbenfadd/data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/hbenfadd/data
      o: bind
networks:
  inception:
