version: '3.8'

services:
  wordpress:
    image: wordpress 
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      inception:
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      inception:
    depends_on:
      - wordpress
      - adminer

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
    networks:
      inception:
  adminer:
    image: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    networks:
      inception:

  ftp:
    image: ftp 
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    networks:
      inception:
    ports:
      - "21:21"
    volumes:
      - wordpress-data:/var/www/wordpress
    env_file:
      - ./.env

  static_page:
    image: static_page
    build:
      context: ./requirements/bonus/static_page
      dockerfile: Dockerfile
    container_name: static_page
    networks:
      inception:
    ports:
      - "80:3000"

  redis:
    image: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      inception:

  elasticsearch:
    image: elasticsearch
    build:
      context: ./requirements/bonus/elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    networks:
      inception:

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb-data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress-data
      o: bind

networks:
  inception:

